# Generated by Django 3.2.20 on 2023-08-03 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_first_name', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_last_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('min_people', models.IntegerField()),
                ('max_people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.DateField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_name', to='booking.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_table', to='booking.table')),
            ],
        ),
    ]
