# Generated by Django 3.2.20 on 2023-08-04 18:10

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='email@hrestaurant.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=15, null=True, unique=True)),
                ('number_of_people', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField(default=datetime.datetime(2023, 8, 4, 18, 10, 6, 773938, tzinfo=utc))),
                ('time', models.CharField(choices=[('11:00:00', '11am'), ('11:30:00', '11:30am'), ('12:00:00', '12pm'), ('12:30:00', '12:30pm'), ('13:00:00', '1pm'), ('13:30:00', '1:30pm'), ('14:00:00', '2pm'), ('14:30:00', '2:30pm'), ('15:00:00', '3pm'), ('15:30:00', '3:30pm'), ('16:00:00', '4pm'), ('16:30:00', '4:30pm'), ('17:00:00', '5pm'), ('17:30:00', '5:30pm'), ('18:00:00', '6pm'), ('18:30:00', '6:30pm'), ('19:00:00', '7pm'), ('19:30:00', '7:30pm'), ('20:00:00', '8pm'), ('20:30:00', '8:30pm'), ('21:00:00', '9pm'), ('21:30:00', '9:30pm'), ('22:00:00', '10pm')], default=datetime.datetime(2023, 8, 4, 18, 10, 6, 773963, tzinfo=utc), max_length=10)),
                ('special_requests', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
