# Generated by Django 3.2.20 on 2023-08-12 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20230809_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 12, 16, 16, 35, 871593, tzinfo=utc)),
        ),
    ]
